### ISSUE TITLE
Boost + CMake: the unholy union

### ISSUE THREAD

**Issue by jkbonfield** [mitogen/gabac#1]
Gabac seems virtually impossible to build unless you're root (either for real or within a VM).
The system boost libraries on all machines I've tried rarely seem to contan a sufficient set of libraries.

I tried building the entirety of boost and installed it to $BOOST_ROOT.

However absolutely whatever I do cmake is finding both the system one and my local one and flailing badly.  There are meant to be ways to stop this, but try hard as I can it just doesn't work for me.

```
$ mkdir build
$ cd build
$ cmake .. -DBoost_NO_SYSTEM_PATHS=TRUE -DBOOST_ROOT=$BOOST_ROOT
```

Output:

```
-- CMake generator: Unix Makefiles
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- GABAC_BUILD_SHARED_LIB=
-- CMAKE_CXX_COMPILER_ID=GNU
-- Build type not specified
-- Using fall-back build type 'Debug'
-- C++ compiler flags:  -pedantic -Wall -Wextra -Wshadow -Wstrict-aliasing -Ofast
-- Additional C++ compiler flags for build type 'Debug': -g
-- Additional C++ compiler flags for build type 'Release': -O3 -DNDEBUG
-- Additional C++ compiler flags for build type 'RelWithDebInfo': -O2 -g -DNDEBUG
-- Additional C++ compiler flags for build type 'MinSizeRel': -Os -DNDEBUG
-- Selected build type: Debug
CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:72 (find_package)


CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:72 (find_package)

...
```

The workarounds listed at https://stackoverflow.com/questions/3016448/how-can-i-get-cmake-to-find-my-alternative-boost-installation/13862264#13862264 don't seem to be working either.  Is this telling me my cmake is broken, or the CMakeLists.txt file here?

OS is Ubuntu Bionic.

I did once get this working by installing a new Ubuntu machine into a VM and "apt get install"ing the boost packages manually.  So the Gabac code is fine, it's just the monstrosity of cmake+boost that's making this such a herculean task.   CMake is great up to the point you need to configure anything; then it's wrestling an angry crocodile!

Any chance of an autoconf equivalent too with a "--with-boost=DIR" option?

**Comment by jkbonfield** [comment]
Update, it turns out it *is* possible to override BOOST_ROOT with CMake, but the version of cmake I had didn't support the version of Boost I had so the error wasn't so much system Boost vs local Boost conflicts but cmake findBoost vs local Boost conflicts.

Argh!  Isn't this sort of version hell the whole reason for having a build configuration system?  The most challenging part of this entire process has been getting the build configuration system itself to work!

Anyway, it did build, at last.

Please consider this a request to use a sane build system. :-)

**Comment by voges** [comment]
Hi James,

Thanks for pointing us to the inconveniences that the combination of Boost and CMake can bring forth. 

First of all, a couple of notes on the use of Boost. [We had lengthy discussions about whether to use it at all...]

* The GABAC library does not depend on Boost, only the gabacify application, where Boost is used for program options parsing and JSON parsing/reading/writing. We are well aware that there are other libraries out there for either task. However, when thinking about portability - also to non-UNIX-like systems - Boost is likely the way to go, as (parts of) Boost frequently are adopted in editions of the C++ standard.
* We are continuously testing GABAC on Linux (Ubuntu) and macOS with Travis CI. Building works just fine on either system. I also did a test build on an openSUSE system and after installing Boost via ``zypper in *boost*`` the GABAC build works just fine.

Nevertheless, I am well aware that linking to Boost on different systems (probably administrated by other people) can be a tedious task. So please have a look at the latests commits on the develop branch:

By running

    mkdir build
    cd build
    cmake .. -DGABAC_USE_NO_SYSTEM_BOOST=ON
    make gabacify

Boost is freshly downloaded from its Git repository and cleanly built within the ``build`` directory. The download might take a while; however, by using this option the build is entirely self-contained.

NB: As Boost::log linkage is especially intricated, I also edited our log macros to just refer to ``std::cout`` and ``std::cerr``, respectively.

Please let me know if this alternative works for you.

Best regards,
Jan

**Comment by jkbonfield** [comment]
Boost is indeed easy if you're root; yum install, apt-get install, zypper install, etc.  That's no problem and so it's also why it's trivial to use within Travis and Circle-CI.  My problems came about with attempting to install my own copy of boost to avoid either systems with outdated boost or incomplete boost installations. 

That's where it gets exceptionally hard work!  As in hours of frustration.  This isn't a gripe at GABAC, but at the woeful state of Boost support in Cmake.  The ability to build with "-DGABAC_USE_NO_SYSTEM_BOOST=ON" sounds like a great addition - thanks.  It would be more useful though if it had the ability to point it to an already existing local install of Boost as downloading and compiling every time will take an hour or more.  I still also wonder how this works around the issues of cmake and boost incompatibilities?

I naively just downloaded the latest Boost version, but didn't realise it would also require downloading the latest Cmake version because the two are inexplicably linked by the FindBoost cmake module. Gah!

There are some ways this could be mitigated too by listing upfront every single package it needs.  You already have enough information on this as it'll be in the travis config (I see it there).  It would be helpful if this was hoiked out and into an INSTALL file detailing package dependencies so at least we only have one set of things to request to our systems people instead of the more trial and error approach of let it die, ask for a package, and try again cycle.

PS.  All of this could be avoided with a plain old editable Makefile ;-)

**Comment by voges** [comment]
Hi James,

Agreed that a plain old Makefile would probably avoid these problems. However, as we are developing mainly with KDevelop and CLion, I am afraid there are not enough arguments in the direction of circumventing CMake. ;)

However, thanks for proposing a listing of build requirements. I've just added the file ``BUILD.md`` to the ``develop`` branch which is listing the requirements for macOS with Homebrew and for Ubuntu.

When using ``-DGABAC_USE_NO_SYSTEM_BOOST``the download takes around 5 minutes with my (wireless) connection. It needs to be done only once for the first build after a ``git clone``. Thus, I would now close this issue, but we'll keep your feedback in mind when further developing our build system. [We are already planning other quite major changes to the build system...]

Best regards,
Jan

**Comment by jkbonfield** [comment]
Noted and thanks for the remedies.
